# D-1/ D-2

## Text Preprocessing in NLP

In [51]:
import re
import nltk
import numpy as np

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [2]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/jupyter/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [3]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /home/jupyter/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [4]:
stop_words= set(stopwords.words('english'))
len(stop_words)

198

In [5]:
lemm = WordNetLemmatizer()
lemm

<WordNetLemmatizer>

In [6]:
texts = [
    "I love this product!!! 😍",
    "Worst service ever... 0/10",
    "Call me at 9876543210",
    "Visit http://example.com now!",
    "This is AMAZING!!!"
]

In [7]:
def clean_text(text):
    text= text.lower()
    text= re.sub(r'http\S+', '', text)
    text= re.sub(r'\d+', '', text)
    text= re.sub(r'[^\w\s]', '', text)
    text= re.sub(r'\s+', ' ', text)
    words= text.split()
    words= [w for w in words if w not in stop_words]
    words= [lemm.lemmatize(w) for w in words]
    return " ".join(words)

In [8]:
cleaned= [clean_text(t) for t in texts]
cleaned

['love product', 'worst service ever', 'call', 'visit', 'amazing']

In [9]:
for i,j in zip(texts, cleaned):
    print(f"Original: {i}")
    print(f"Cleaned: {j}")

Original: I love this product!!! 😍
Cleaned: love product
Original: Worst service ever... 0/10
Cleaned: worst service ever
Original: Call me at 9876543210
Cleaned: call
Original: Visit http://example.com now!
Cleaned: visit
Original: This is AMAZING!!!
Cleaned: amazing


# D-3

## BoW and N-grams

Real Understanding (MOST IMPORTANT)

👉 BoW = Count of words in fixed vocabulary
👉 N-grams = add context
👉 Vector = numerical representation of text

⚠️ Limitations of BoW
No importance weighting ❌
Common words dominate ❌
No deep meaning ❌


What “No Importance Weighting” Means
BoW does NOT distinguish between:

    important words
    common/useless words
👉 It just counts everything blindly   

👉 So it assumes:
More frequency = more important

### Code (BoW)

In [10]:
texts = ["I love NLP", "I love ML", "I hate NLP"]

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

In [13]:
# "I" is missing because CountVectorizer by default ignores words with less than 2 characters.
# CountVectorizer sorts vocabulary alphabetically, not based on sequence.
vectorizer.get_feature_names_out()

array(['hate', 'love', 'ml', 'nlp'], dtype=object)

In [14]:
X.toarray()

array([[0, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1]])

### Add N-grams to BoW

In [1]:
texts = ["I love love NLP", "I love ML", "I hate NLP"]

In [16]:
vectorizer = CountVectorizer(ngram_range=(1,2)) # unigram + bigram
X = vectorizer.fit_transform(texts)

In [17]:
vectorizer.get_feature_names_out()

array(['hate', 'hate nlp', 'love', 'love love', 'love ml', 'love nlp',
       'ml', 'nlp'], dtype=object)

In [18]:
X.toarray()

array([[0, 0, 2, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 1]])

# D-4

## TF-IDF

In [10]:
texts = ["I love NLP", "I love ML", "I hate NLP", "I do not love NLP"]

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
vectorizer= TfidfVectorizer()
X= vectorizer.fit_transform(texts)

In [13]:
vectorizer.get_feature_names_out()

array(['do', 'hate', 'love', 'ml', 'nlp', 'not'], dtype=object)

In [14]:
X.toarray()

array([[0.        , 0.        , 0.70710678, 0.        , 0.70710678,
        0.        ],
       [0.        , 0.        , 0.53802897, 0.84292635, 0.        ,
        0.        ],
       [0.        , 0.84292635, 0.        , 0.        , 0.53802897,
        0.        ],
       [0.59603894, 0.        , 0.38044393, 0.        , 0.38044393,
        0.59603894]])

## TF-IDF with N-grams

In [20]:
vectorizer = TfidfVectorizer(ngram_range=(1,2))  # unigram + bigram
X = vectorizer.fit_transform(texts)

In [21]:
vectorizer.get_feature_names_out()

array(['do', 'do not', 'hate', 'hate nlp', 'love', 'love ml', 'love nlp',
       'ml', 'nlp', 'not', 'not love'], dtype=object)

In [22]:
X.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.53256952,
        0.        , 0.65782931, 0.        , 0.53256952, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.41137791,
        0.64450299, 0.        , 0.64450299, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.64450299, 0.64450299, 0.        ,
        0.        , 0.        , 0.        , 0.41137791, 0.        ,
        0.        ],
       [0.42888787, 0.42888787, 0.        , 0.        , 0.27375357,
        0.        , 0.33814012, 0.        , 0.27375357, 0.42888787,
        0.42888787]])

N-gram → feature generator
BoW → counting method
TF-IDF → weighting method

N-grams are used along with vectorization techniques like Bag of Words or TF-IDF to capture word sequences and improve context representation.

👉 BoW = counts (integers)      0, 1, 2, 3...
👉 TF-IDF = importance (decimals)     0.0 to 1.0 (or sometimes slightly higher depending on scaling)

## Text Classification Model

#### 1️⃣ Sample Dataset

In [23]:
texts = [
    "I love this product",
    "This is amazing",
    "Worst service ever",
    "I hate this",
    "Very bad experience",
    "I really liked it"
]

labels = [1, 1, 0, 0, 0, 1]  
# 1 = Positive, 0 = Negative

#### 2️⃣ Cleaning Function

In [24]:
stop_words= set(stopwords.words('english'))
len(stop_words)
lemm = WordNetLemmatizer()
lemm

<WordNetLemmatizer>

In [25]:
cleaned= [clean_text(t) for t in texts]
cleaned

['love product',
 'amazing',
 'worst service ever',
 'hate',
 'bad experience',
 'really liked']

#### 3️⃣ Convert Text → Numbers (TF-IDF)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer= TfidfVectorizer(ngram_range=(1,2))
X= vectorizer.fit_transform(cleaned)

In [27]:
vectorizer.get_feature_names_out()

array(['amazing', 'bad', 'bad experience', 'ever', 'experience', 'hate',
       'liked', 'love', 'love product', 'product', 'really',
       'really liked', 'service', 'service ever', 'worst',
       'worst service'], dtype=object)

In [28]:
X.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.57735027, 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.4472136 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4472136 , 0.4472136 , 0.4472136 ,
        0.4472136 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 

#### 4️⃣ Train Model

In [29]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X, labels)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [30]:
labels

[1, 1, 0, 0, 0, 1]

#### 5️⃣ Make Prediction

In [31]:
test = ["this product is bad"]

test_clean = [clean_text(t) for t in test]
test_vec = vectorizer.transform(test_clean)
test_vec.toarray()

array([[0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.70710678,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [32]:
prediction = model.predict(test_vec)
prob = model.predict_proba(test_vec)
prediction, prob

(array([0]), array([[0.5, 0.5]]))

#### Check important words learned

In [33]:
feature_names= vectorizer.get_feature_names_out()
feature_names

array(['amazing', 'bad', 'bad experience', 'ever', 'experience', 'hate',
       'liked', 'love', 'love product', 'product', 'really',
       'really liked', 'service', 'service ever', 'worst',
       'worst service'], dtype=object)

In [34]:
coeffs= model.coef_[0]
coeffs

array([ 0.40109589, -0.23157282, -0.23157282, -0.17937554, -0.23157282,
       -0.40109589,  0.23157282,  0.23157282,  0.23157282,  0.23157282,
        0.23157282,  0.23157282, -0.17937554, -0.17937554, -0.17937554,
       -0.17937554])

In [38]:
for word, coef in zip(feature_names, coeffs):
    print(f"{word} : {coef}")
# 👉 Positive coef → positive sentiment
# 👉 Negative coef → negative sentiment

amazing : 0.4010958939786973
bad : -0.23157282235945448
bad experience : -0.23157282235945448
ever : -0.17937553688648314
experience : -0.23157282235945448
hate : -0.4010958939786973
liked : 0.23157282235945448
love : 0.23157282235945448
love product : 0.23157282235945448
product : 0.23157282235945448
really : 0.23157282235945448
really liked : 0.23157282235945448
service : -0.17937553688648314
service ever : -0.17937553688648314
worst : -0.17937553688648314
worst service : -0.17937553688648314


Interview Answer (GOLD)

I preprocess text, convert it into numerical features using TF-IDF with n-grams, and train a Logistic Regression model for classification.

Using only bigrams can lose important single-word information, so it’s best to use a combination of unigrams and bigrams.

Both BoW and TF-IDF use a fixed vocabulary learned during training, and unseen words in test data are ignored.

# D-5

## Embeddings

Embeddings are vector representations of words, and Word2Vec is one model used to generate those embeddings.

### Word2Vec in the easiest way possible using gensim

#### 1️⃣ Install (only once)

In [1]:
pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.6/27.6 MB 81.4 MB/s  0:00:006m0:00:010:01
Note: you may need to restart the kernel to use updated packages.


#### 2️⃣ Sample Data (very important format)

👉 Word2Vec needs tokenized sentences (list of words)

In [2]:
sentences = [
    ["i", "love", "nlp"],
    ["i", "love", "machine", "learning"],
    ["nlp", "is", "fun"],
    ["machine", "learning", "is", "powerful"],
    ["i", "enjoy", "learning"]
]

#### 3️⃣ Train Word2Vec Model

In [4]:
from gensim.models import Word2Vec

model = Word2Vec(
    sentences,
    vector_size=50,   # size of embedding
    window=3,         # context window
    min_count=1,      # include all words
    workers=4
)

In [5]:
model

#### 4️⃣ Get Word Embedding

In [6]:
model.wv["love"]

array([ 2.8740549e-03, -5.2920175e-03, -1.4147566e-02, -1.5610614e-02,
       -1.8243574e-02, -1.1870339e-02, -3.6948491e-03, -8.6477427e-03,
       -1.2921341e-02, -7.4346447e-03,  8.5783172e-03, -7.4780867e-03,
        1.6756350e-02,  3.0679870e-03, -1.4484639e-02,  1.8867597e-02,
        1.5262425e-02,  1.0986564e-02, -1.3697691e-02,  1.1645358e-02,
        8.0181863e-03,  1.0370739e-02,  8.5118031e-03,  3.8795089e-03,
       -6.3403249e-03,  1.6707690e-02,  1.9224361e-02,  7.5852061e-03,
       -5.6739901e-03,  1.4255047e-05,  2.4376370e-03, -1.6916649e-02,
       -1.6447891e-02, -4.6203137e-04,  2.4745751e-03, -1.1486761e-02,
       -9.4505474e-03, -1.4692149e-02,  1.6657231e-02,  2.4259568e-04,
       -9.0187974e-03,  1.1403411e-02,  1.8360030e-02, -8.1997439e-03,
        1.5929364e-02,  1.0750868e-02,  1.1758246e-02,  1.0251808e-03,
        1.6426168e-02, -1.4038081e-02], dtype=float32)

#### 5️⃣ Find Similar Words (MOST IMPORTANT 🔥)

In [7]:
model.wv.most_similar("love")

[('enjoy', 0.18339458107948303),
 ('nlp', 0.10232102125883102),
 ('powerful', 0.029594380408525467),
 ('i', 0.018277142196893692),
 ('learning', 0.012442175298929214),
 ('is', -0.02784133516252041),
 ('fun', -0.10186850279569626),
 ('machine', -0.2091004103422165)]

In [13]:
model.wv.most_similar("hi")

KeyError: "Key 'hi' not present in vocabulary"

#### 6️⃣ Check similarity between words

In [10]:
model.wv.similarity("love", "enjoy")

0.1833946

#### 7️⃣ Convert sentence → vector

In [11]:
model.wv

In [12]:
import numpy as np

def sentence_vector(sentence):
    vectors = [model.wv[word] for word in sentence if word in model.wv]
    return np.mean(vectors, axis=0)

vec = sentence_vector(["i", "love", "nlp"])
print(vec)

[-0.00441755  0.00328474 -0.01201567 -0.00557082  0.00469694 -0.00203396
 -0.00066881 -0.00564542 -0.01221753  0.00792445 -0.00128388 -0.00438785
  0.0090326  -0.00351687 -0.00083975  0.00388635  0.0079358   0.01396651
 -0.01203281  0.0019647   0.00160003  0.00577911 -0.00065094 -0.01053639
  0.006104    0.00272113  0.01698514  0.00549459 -0.00801696 -0.00319201
  0.00388827 -0.00870553 -0.00681882  0.00289761 -0.00872771 -0.00364409
  0.0006401  -0.00589629  0.00444216  0.004025   -0.00564799  0.00508133
  0.00783752  0.00194106  0.0143714   0.00997701 -0.00106931 -0.00615255
  0.00316515 -0.00110572]


# D-6

## Sentence embeddings and Semantic similarity 

### Sentence Transformers Code

In [1]:
# pip install sentence-transformers

In [2]:
# pip install -U sentence-transformers transformers peft

In [39]:
sentences = [
    "I love machine learning",
    "I enjoy machine learning",
    "I hate machine learning"
]

In [40]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
# It loads a pre-trained sentence embedding model
model= SentenceTransformer('all-MiniLM-L6-v2') 
model

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [15]:
embeddings = model.encode(["I love NLP"])
len(embeddings)

1

In [16]:
embeddings

array([[-4.13824059e-03, -2.96884310e-02,  5.89311719e-02,
        -4.00694944e-02,  8.18729922e-02,  2.78291595e-03,
         6.77006245e-02,  4.80398387e-02,  6.54386953e-02,
         3.86305600e-02, -9.38962027e-03, -1.80722680e-02,
        -6.96899742e-02,  6.42963126e-02,  1.92712191e-02,
         8.19071382e-02, -2.53259614e-02,  6.97748910e-04,
        -3.26028243e-02, -3.14748734e-02, -5.51633537e-02,
         1.23413399e-01,  3.20147141e-03, -6.44584224e-02,
         3.23913135e-02,  3.48860696e-02, -1.99929532e-02,
        -2.39631534e-02, -3.77598335e-03,  2.16638134e-03,
        -2.34584673e-03,  5.20627424e-02,  1.54693406e-02,
         4.19374928e-02, -4.15189415e-02,  3.16199474e-02,
         2.05578599e-02,  1.90055221e-02,  2.61998251e-02,
         6.31199181e-02, -3.00359260e-02, -1.48233511e-02,
        -4.26205024e-02,  3.58042903e-02, -2.43018824e-03,
         2.06025839e-02, -4.44827676e-02,  4.16266732e-02,
         1.22225862e-02,  5.75128105e-03,  4.51941928e-0

In [50]:
print(embeddings.shape)
# Yes, 384 represents the number of features (dimensions)/ columns in the embedding vector for each sentence.
# Dimension = model architecture choice
# 384 = vector size of model, Each sentence → 384 features

(3, 384)


In [42]:
embeddings = model.encode(sentences)
len(embeddings)

3

In [43]:
embeddings

array([[-0.04363634, -0.05905434,  0.08201233, ...,  0.09771024,
         0.0168808 , -0.09040584],
       [-0.04161281, -0.06530578,  0.07284426, ...,  0.06571472,
        -0.011806  , -0.06757642],
       [-0.00042754, -0.00489234,  0.09270904, ...,  0.0424214 ,
        -0.0017913 , -0.05403112]], dtype=float32)

In [44]:
sentences

['I love machine learning',
 'I enjoy machine learning',
 'I hate machine learning']

In [45]:
# similarity between sentence 1 and others
sim= cosine_similarity([embeddings[0]], embeddings)
sim

array([[1.        , 0.9143261 , 0.80050313]], dtype=float32)

In [46]:
# similarity between all
sim_matrix= cosine_similarity(embeddings)
sim_matrix

array([[1.        , 0.91432613, 0.800503  ],
       [0.91432613, 0.99999976, 0.7861057 ],
       [0.800503  , 0.7861057 , 0.99999964]], dtype=float32)

#### Test

In [69]:
test = ["I hate this product"]
test_embedding= model.encode(test)
sim = cosine_similarity(test_embedding, embeddings)
sim

array([[0.2679196 , 0.21191883, 0.46215463]], dtype=float32)

In [70]:
best_ind= np.argmax(sim)
sentences[best_ind]

'I hate machine learning'

#### Find most similar sentence

In [71]:
query = "I like machine learning"
query_emb = model.encode([query])
query_emb

array([[-6.85173050e-02, -7.87255839e-02,  5.66141792e-02,
         4.93533025e-03,  3.27079259e-02, -4.20423932e-02,
         2.18797140e-02, -1.33790895e-02,  2.51393914e-02,
         1.21298507e-02, -2.61036176e-02,  2.94081457e-02,
         2.50682253e-02, -5.97490231e-03, -2.02341657e-02,
         2.06228346e-02, -1.62279364e-02,  1.36305895e-02,
        -8.41802731e-02, -1.27319127e-01, -8.49098787e-02,
         3.20805721e-02,  2.64962506e-03, -3.76693485e-03,
         1.82175133e-02,  5.20232394e-02,  2.06903014e-02,
         9.41525027e-03,  2.92243436e-02, -6.67435005e-02,
        -2.58102156e-02,  1.89452227e-02,  1.86318662e-02,
         9.72532853e-03, -9.14161652e-02, -5.31712547e-04,
         6.59263739e-03,  4.10127416e-02,  1.98435877e-03,
         1.95787232e-02, -3.40205133e-02, -3.13353427e-02,
         2.14087293e-02,  9.49033443e-03,  6.79720119e-02,
         4.82687466e-02, -4.19171788e-02, -8.02870393e-02,
         5.48039041e-02,  5.73328994e-02, -6.79085404e-0

In [72]:
similarities = cosine_similarity(query_emb, embeddings)
similarities

array([[0.924297  , 0.9088551 , 0.79901993]], dtype=float32)

In [73]:
best_idx= np.argmax(similarities)
best_idx

0

In [74]:
print("Most similar sentence:", sentences[best_idx])

Most similar sentence: I love machine learning


# BERT